/**
 * tickerDatabase.js
 * Base de dados para busca inteligente (autocomplete)
 * Mapeia Nomes de empresas para seus Tickers (B3 e Global)
 */

export const TICKER_DATABASE = [
  // BRASILEIRAS (B3)
  { ticker: 'PETR4', name: 'Petróleo Brasileiro S.A. - Petrobras', sector: 'Energia' },
  { ticker: 'PETR3', name: 'Petróleo Brasileiro S.A. - Petrobras', sector: 'Energia' },
  { ticker: 'VALE3', name: 'Vale S.A.', sector: 'Mineração' },
  { ticker: 'ITUB4', name: 'Itaú Unibanco Holding S.A.', sector: 'Financeiro' },
  { ticker: 'BBDC4', name: 'Banco Bradesco S.A.', sector: 'Financeiro' },
  { ticker: 'BBDC3', name: 'Banco Bradesco S.A.', sector: 'Financeiro' },
  { ticker: 'BBAS3', name: 'Banco do Brasil S.A.', sector: 'Financeiro' },
  { ticker: 'ABEV3', name: 'Ambev', sector: 'Bebidas' },
  { ticker: 'WEGE3', name: 'WEG', sector: 'Industrial' },
  { ticker: 'MGLU3', name: 'Magazine Luiza (Magalu)', sector: 'Varejo' },
  { ticker: 'ITSA4', name: 'Itaúsa', sector: 'Financeiro/Holding' },
  { ticker: 'B3SA3', name: 'B3 - Brasil Bolsa Balcão', sector: 'Financeiro' },
  { ticker: 'RENT3', name: 'Localiza', sector: 'Transporte' },
  { ticker: 'HAPV3', name: 'Hapvida', sector: 'Saúde' },
  { ticker: 'SUZB3', name: 'Suzano', sector: 'Papel e Celulose' },
  { ticker: 'JBSS3', name: 'JBS', sector: 'Alimentos' },
  { ticker: 'GGBR4', name: 'Gerdau', sector: 'Siderurgia' },
  { ticker: 'BPAC11', name: 'BTG Pactual', sector: 'Financeiro' },
  { ticker: 'RAIL3', name: 'Rumo', sector: 'Logística' },
  { ticker: 'RADL3', name: 'Raia Drogasil', sector: 'Saúde' },
  { ticker: 'ELET3', name: 'Eletrobras ON', sector: 'Energia' },
  { ticker: 'ELET6', name: 'Eletrobras PNB', sector: 'Energia' },
  { ticker: 'LREN3', name: 'Lojas Renner', sector: 'Varejo' },
  { ticker: 'CSNA3', name: 'Siderúrgica Nacional', sector: 'Siderurgia' },
  { ticker: 'EQTL3', name: 'Equatorial Energia', sector: 'Energia' },
  { ticker: 'TIMS3', name: 'TIM Brasil', sector: 'Telecom' },
  { ticker: 'VIVT3', name: 'Telefônica Brasil (Vivo)', sector: 'Telecom' },
  { ticker: 'UGPA3', name: 'Ultrapar (Ipiranga)', sector: 'Energia' },
  { ticker: 'VBBR3', name: 'Vibra Energia', sector: 'Energia' },
  { ticker: 'PRIO3', name: 'PetroRio', sector: 'Energia' },
  { ticker: 'EGIE3', name: 'Engie Brasil', sector: 'Energia' },
  { ticker: 'CPFE3', name: 'CPFL Energia', sector: 'Energia' },
  { ticker: 'SANB11', name: 'Santander Brasil', sector: 'Financeiro' },
  { ticker: 'CMIG4', name: 'Cemig PN', sector: 'Energia' },
  { ticker: 'CSAN3', name: 'Cosan', sector: 'Energia/Holding' },
  { ticker: 'RAIZ4', name: 'Raízen', sector: 'Energia' },
  { ticker: 'ASAI3', name: 'Assaí Atacadista', sector: 'Varejo' },
  { ticker: 'NTCO3', name: 'Natura &Co', sector: 'Cosméticos' },
  { ticker: 'TOTS3', name: 'Totvs', sector: 'Tecnologia' },
  { ticker: 'BRFS3', name: 'BRF S.A.', sector: 'Alimentos' },
  { ticker: 'AZUL4', name: 'Azul Linhas Aéreas', sector: 'Transporte' },
  { ticker: 'GOLL4', name: 'Gol Linhas Aéreas', sector: 'Transporte' },
  { ticker: 'CVCB3', name: 'CVC Viagens', sector: 'Turismo' },
  { ticker: 'MRFG3', name: 'Marfrig', sector: 'Alimentos' },
  { ticker: 'EMBR3', name: 'Embraer', sector: 'Aeroespacial' },
  { ticker: 'BRKM5', name: 'Braskem', sector: 'Química' },
  { ticker: 'ENEV3', name: 'Eneva', sector: 'Energia' },
  { ticker: 'TAEE11', name: 'Taesa', sector: 'Energia' },
  { ticker: 'ALPA4', name: 'Alpargatas (Havaianas)', sector: 'Vestuário' },
  { ticker: 'COGN3', name: 'Cogna Educação', sector: 'Educação' },
  { ticker: 'YDUQ3', name: 'YDUQS (Estácio)', sector: 'Educação' },
  { ticker: 'IRBR3', name: 'IRB Brasil RE', sector: 'Seguros' },
  { ticker: 'ABCB4', name: 'Banco ABC Brasil', sector: 'Financeiro' },
  { ticker: 'ALUP11', name: 'Alupar', sector: 'Energia' },
  { ticker: 'AMBP3', name: 'Ambipar', sector: 'Serviços' },
  { ticker: 'ARZZ3', name: 'Arezzo', sector: 'Consumo' },
  { ticker: 'BEEF3', name: 'Minerva', sector: 'Alimentos' },
  { ticker: 'BRAP4', name: 'Bradespar', sector: 'Investimentos' },
  { ticker: 'BRIT3', name: 'Brisanet', sector: 'Telecom' },
  { ticker: 'CCRO3', name: 'CCR', sector: 'Infraestrutura' },
  { ticker: 'CEAB3', name: 'C&A Modas', sector: 'Varejo' },
  { ticker: 'CIEL3', name: 'Cielo', sector: 'Tecnologia/Financeiro' },
  { ticker: 'COCE5', name: 'Coelce', sector: 'Energia' },
  { ticker: 'CPLE6', name: 'Copel PNB', sector: 'Energia' },
  { ticker: 'CPLE3', name: 'Copel ON', sector: 'Energia' },
  { ticker: 'CRFB3', name: 'Carrefour Brasil', sector: 'Varejo' },
  { ticker: 'CURY3', name: 'Cury Construtora', sector: 'Imobiliário' },
  { ticker: 'CYRE3', name: 'Cyrela', sector: 'Imobiliário' },
  { ticker: 'DIRR3', name: 'Direcional', sector: 'Imobiliário' },
  { ticker: 'DXCO3', name: 'Dexco (Duratex)', sector: 'Industrial' },
  { ticker: 'ENBR3', name: 'EDP Brasil', sector: 'Energia' },
  { ticker: 'ENGI11', name: 'Energisa', sector: 'Energia' },
  { ticker: 'ESPA3', name: 'Espaçolaser', sector: 'Serviços' },
  { ticker: 'EZTC3', name: 'EZTEC', sector: 'Imobiliário' },
  { ticker: 'FLRY3', name: 'Fleury', sector: 'Saúde' },
  { ticker: 'GRND3', name: 'Grendene', sector: 'Vestuário' },
  { ticker: 'HYPE3', name: 'Hypera Pharma', sector: 'Saúde' },
  { ticker: 'IGTI11', name: 'Iguatemi', sector: 'Imobiliário' },
  { ticker: 'JHSF3', name: 'JHSF', sector: 'Imobiliário' },
  { ticker: 'KEPL3', name: 'Kepler Weber', sector: 'Industrial' },
  { ticker: 'KLBN11', name: 'Klabin', sector: 'Papel e Celulose' },
  { ticker: 'LOGG3', name: 'LOG CP', sector: 'Imobiliário' },
  { ticker: 'MDIA3', name: 'M. Dias Branco', sector: 'Alimentos' },
  { ticker: 'MOVI3', name: 'Movida', sector: 'Transporte' },
  { ticker: 'MULT3', name: 'Multiplan', sector: 'Imobiliário' },
  { ticker: 'NEOE3', name: 'Neoenergia', sector: 'Energia' },
  { ticker: 'ODPV3', name: 'Odontoprev', sector: 'Saúde' },
  { ticker: 'ONCO3', name: 'Oncoclinicas', sector: 'Saúde' },
  { ticker: 'ORVR3', name: 'Orizon', sector: 'Serviços' },
  { ticker: 'PARD3', name: 'Hermes Pardini', sector: 'Saúde' },
  { ticker: 'PETZ3', name: 'Petz', sector: 'Varejo' },
  { ticker: 'PLAS3', name: 'Plascar', sector: 'Industrial' },
  { ticker: 'PSSA3', name: 'Porto Seguro', sector: 'Seguros' },
  { ticker: 'QUAL3', name: 'Qualicorp', sector: 'Saúde' },
  { ticker: 'SBSP3', name: 'Sabesp', sector: 'Saneamento' },
  { ticker: 'SIMH3', name: 'Simpar', sector: 'Logística' },
  { ticker: 'SLCE3', name: 'SLC Agrícola', sector: 'Agronegócio' },
  { ticker: 'SMTO3', name: 'São Martinho', sector: 'Agronegócio' },
  { ticker: 'STBP3', name: 'Santos Brasil', sector: 'Logística' },
  { ticker: 'TEND3', name: 'Construtora Tenda', sector: 'Imobiliário' },
  { ticker: 'TRPL4', name: 'ISA CTEEP', sector: 'Energia' },
  { ticker: 'UNIP6', name: 'Unipar', sector: 'Química' },
  { ticker: 'USIM5', name: 'Usiminas', sector: 'Siderurgia' },
  { ticker: 'VAMO3', name: 'Vamos', sector: 'Logística' },
  { ticker: 'VULC3', name: 'Vulcabras', sector: 'Vestuário' },
  { ticker: 'ZAMP3', name: 'Zamp (Burger King)', sector: 'Consumo' },
  { ticker: 'SOJA3', name: 'Boa Safra Sementes S.A.', sector: 'Agronegócio' },
  { ticker: 'AGRO3', name: 'BrasilAgro - Cia Bras de Propriedades Agrícolas', sector: 'Agronegócio' },
  { ticker: 'LAND3', name: 'Terra Santa', sector: 'Agronegócio' },

  // INTERNACIONAIS (USA)
  { ticker: 'AAPL', name: 'Apple Inc.', sector: 'Tecnologia' },
  { ticker: 'AAPL34', name: 'Apple (BDR)', sector: 'Tecnologia' },
  { ticker: 'MSFT', name: 'Microsoft Corp.', sector: 'Tecnologia' },
  { ticker: 'MSFT34', name: 'Microsoft (BDR)', sector: 'Tecnologia' },
  { ticker: 'GOOGL', name: 'Alphabet Inc. (Google)', sector: 'Tecnologia' },
  { ticker: 'GOGL34', name: 'Google (BDR)', sector: 'Tecnologia' },
  { ticker: 'AMZN', name: 'Amazon.com', sector: 'Consumo' },
  { ticker: 'AMZO34', name: 'Amazon (BDR)', sector: 'Consumo' },
  { ticker: 'TSLA', name: 'Tesla Inc.', sector: 'Automotivo' },
  { ticker: 'TSLA34', name: 'Tesla (BDR)', sector: 'Automotivo' },
  { ticker: 'META', name: 'Meta Platforms (Facebook/Instagram)', sector: 'Tecnologia' },
  { ticker: 'M1TA34', name: 'Meta (BDR)', sector: 'Tecnologia' },
  { ticker: 'NVDA', name: 'NVIDIA Corp.', sector: 'Tecnologia' },
  { ticker: 'NVDC34', name: 'NVIDIA (BDR)', sector: 'Tecnologia' },
  { ticker: 'NFLX', name: 'Netflix Inc.', sector: 'Entretenimento' },
  { ticker: 'BRK.B', name: 'Berkshire Hathaway', sector: 'Investimentos' },
  { ticker: 'V', name: 'Visa Inc.', sector: 'Financeiro' },
  { ticker: 'MA', name: 'Mastercard', sector: 'Financeiro' },
  { ticker: 'WMT', name: 'Walmart', sector: 'Varejo' },
  { ticker: 'DIS', name: 'Walt Disney Co.', sector: 'Entretenimento' },
  { ticker: 'JPM', name: 'JPMorgan Chase', sector: 'Financeiro' },
  { ticker: 'KO', name: 'Coca-Cola Co.', sector: 'Bebidas' },
  { ticker: 'PEP', name: 'PepsiCo', sector: 'Bebidas' },
  { ticker: 'COST', name: 'Costco Wholesale', sector: 'Varejo' },
  { ticker: 'IBM', name: 'IBM Corp.', sector: 'Tecnologia' },
  { ticker: 'NKE', name: 'Nike Inc.', sector: 'Artigos Esportivos' },
  { ticker: 'INTC', name: 'Intel Corp.', sector: 'Tecnologia' },
  { ticker: 'AMD', name: 'AMD', sector: 'Tecnologia' },
  { ticker: 'CRM', name: 'Salesforce', sector: 'Tecnologia' },
];

export const searchTicker = (query) => {
  if (!query || query.length < 2) return [];
  
  const normalizedQuery = query.toLowerCase().trim();
  
  return TICKER_DATABASE.filter(item => 
    item.ticker.toLowerCase().includes(normalizedQuery) || 
    item.name.toLowerCase().includes(normalizedQuery)
  ).slice(0, 8); // Limitar a 8 sugestões para manter o layout limpo
};
